// Preload bridge — exposes a minimal, typed IPC surface to the renderer.
// contextIsolation is on, so the renderer sees only `window.editor` with these
// methods, never Node or the raw ipcRenderer.
//
// This file stays plain CommonJS JavaScript on purpose. Electron's preload
// loader does not run Node's type-stripping hook — a `.cts` preload is read
// verbatim, so even a bare `const n: number = 1` fails with "Missing
// initializer in const declaration" and the bridge silently never installs.
// The contract it implements is EditorApi in ./ipc.ts; keep the two in step.
const { contextBridge, ipcRenderer } = require('electron');

/** @type {import('./ipc.ts').EditorApi} */
const api = {
  listMaps: () => ipcRenderer.invoke('maps:list'),
  openMapDialog: () => ipcRenderer.invoke('dialog:openMap'),
  newMap: (p) => ipcRenderer.invoke('map:new', p),
  openArchive: (path, inner, stock) => ipcRenderer.invoke('map:open-archive', { path, inner, stock }),
  loadMap: (path) => ipcRenderer.invoke('map:load', path),
  pickSceneFile: () => ipcRenderer.invoke('scene:pick-file'),
  scenesInFile: (file) => ipcRenderer.invoke('scene:in-file', file),
  openScene: (p) => ipcRenderer.invoke('scene:open', p),
  closeMap: () => ipcRenderer.invoke('map:close'),
  moveObject: (id, x, y) => ipcRenderer.invoke('object:move', { id, x, y }),
  rotateObject: (id, r) => ipcRenderer.invoke('object:rotate', { id, r }),
  removeObject: (id) => ipcRenderer.invoke('object:remove', { id }),
  objectProps: (id) => ipcRenderer.invoke('object:props', { id }),
  specValues: (type) => ipcRenderer.invoke('spec:values', { type }),
  setObjectProp: (p) => ipcRenderer.invoke('object:set-prop', p),
  mapProps: () => ipcRenderer.invoke('map:props'),
  setMapProp: (p) => ipcRenderer.invoke('map:set-prop', p),
  roster: (name) => ipcRenderer.invoke('registry:roster', { name }),
  objectsOfClass: (className) => ipcRenderer.invoke('objects:of-class', { className }),
  newEntity: (p) => ipcRenderer.invoke('map:new-entity', p),
  readEntity: (href) => ipcRenderer.invoke('entity:read', { href }),
  setEntityPath: (p) => ipcRenderer.invoke('entity:set-path', p),
  pickText: () => ipcRenderer.invoke('map:pick-text'),
  copyEntityToMap: (href) => ipcRenderer.invoke('entity:copy-to-map', { href }),
  suggestName: (className) => ipcRenderer.invoke('map:suggest-name', { className }),
  names: (kind) => ipcRenderer.invoke('map:names', { kind }),
  mapTree: () => ipcRenderer.invoke('map:tree'),
  // The same tree, rooted at one object — structures a flat property list
  // cannot reach (a hero's army, a capture trigger).
  objectTree: (p) => ipcRenderer.invoke('object:tree', p),
  setObjectPath: (p) => ipcRenderer.invoke('object:set-path', p),
  addObjectItem: (p) => ipcRenderer.invoke('object:add-item', p),
  removeObjectItem: (p) => ipcRenderer.invoke('object:remove-item', p),
  setMapPath: (p) => ipcRenderer.invoke('map:set-path', p),
  addMapItem: (p) => ipcRenderer.invoke('map:add-item', p),
  removeMapItem: (p) => ipcRenderer.invoke('map:remove-item', p),
  setMapList: (p) => ipcRenderer.invoke('map:set-list', p),
  readFile: (href) => ipcRenderer.invoke('map:read-file', { href }),
  scriptContext: () => ipcRenderer.invoke('script:context'),
  mapFiles: (p) => ipcRenderer.invoke('map:files', p),
  writeFile: (p) => ipcRenderer.invoke('map:write-file', p),
  newScript: (p) => ipcRenderer.invoke('script:new', p),
  newSpecialization: (p) => ipcRenderer.invoke('spec:new', p),
  resolveScript: (p) => ipcRenderer.invoke('script:resolve', p),
  locGet: () => ipcRenderer.invoke('loc:get'),
  locEnable: (p) => ipcRenderer.invoke('loc:enable', p),
  locAddLanguage: (p) => ipcRenderer.invoke('loc:add-language', p),
  locRemoveLanguage: (p) => ipcRenderer.invoke('loc:remove-language', p),
  locExport: (p) => ipcRenderer.invoke('loc:export', p),
  listObjects: () => ipcRenderer.invoke('objects:list'),
  objectIcon: (path) => ipcRenderer.invoke('objects:icon', { path }),
  addObject: (p) => ipcRenderer.invoke('object:add', p),
  save: () => ipcRenderer.invoke('map:save'),
  pack: () => ipcRenderer.invoke('map:pack'),
  status: () => ipcRenderer.invoke('map:status'),
  listTiles: () => ipcRenderer.invoke('terrain:tiles'),
  paintTile: (p) => ipcRenderer.invoke('terrain:paint', p),
  paintRiver: (p) => ipcRenderer.invoke('terrain:paint-river', p),
  setRiverCells: (p) => ipcRenderer.invoke('terrain:river-cells', p),
  setMask: (p) => ipcRenderer.invoke('terrain:mask', p),
  sculpt: (p) => ipcRenderer.invoke('terrain:sculpt', p),
  addLayer: (p) => ipcRenderer.invoke('terrain:add-layer', p),
  undo: () => ipcRenderer.invoke('history:undo'),
  redo: () => ipcRenderer.invoke('history:redo'),
  // Campaigns. A campaign is edited as a whole document (see EditorApi), so
  // these carry one CampaignDoc rather than a field at a time.
  listCampaigns: () => ipcRenderer.invoke('campaign:list'),
  newCampaign: (name) => ipcRenderer.invoke('campaign:new', { name }),
  openCampaign: (dir) => ipcRenderer.invoke('campaign:open', { dir }),
  saveCampaign: (doc) => ipcRenderer.invoke('campaign:save', { doc }),
  packCampaign: (dir) => ipcRenderer.invoke('campaign:pack', { dir }),
  mapHeroes: (mapRel) => ipcRenderer.invoke('campaign:map-heroes', { mapRel }),
  // Units/Artifacts mod — game-global, no map needed.
  listMods: () => ipcRenderer.invoke('mods:list'),
  modFormData: () => ipcRenderer.invoke('mods:form-data'),
  modPreset: (donor) => ipcRenderer.invoke('mods:preset', { donor }),
  modArtifactPreset: (donor) => ipcRenderer.invoke('mods:artifact-preset', { donor }),
  buildingData: () => ipcRenderer.invoke('mods:building-data'),
  buildingPreset: (donor) => ipcRenderer.invoke('mods:building-preset', { donor }),
  installBuilding: (p) => ipcRenderer.invoke('mods:install-building', p),
  updateBuilding: (p) => ipcRenderer.invoke('mods:update-building', p),
  removeBuilding: (p) => ipcRenderer.invoke('mods:remove-building', p),
  installMod: (p) => ipcRenderer.invoke('mods:install', p),
  updateMod: (p) => ipcRenderer.invoke('mods:update', p),
  installArtifact: (p) => ipcRenderer.invoke('mods:install-artifact', p),
  installArtifactSet: (p) => ipcRenderer.invoke('mods:install-set', p),
  installHero: (p) => ipcRenderer.invoke('mods:install-hero', p),
  updateHero: (p) => ipcRenderer.invoke('mods:update-hero', p),
  removeHero: (p) => ipcRenderer.invoke('mods:remove-hero', p),
  heroUses: (p) => ipcRenderer.invoke('mods:hero-uses', p),
  installSpecialization: (p) => ipcRenderer.invoke('mods:install-specialization', p),
  installHeroClass: (p) => ipcRenderer.invoke('mods:install-class', p),
  updateHeroClass: (p) => ipcRenderer.invoke('mods:update-class', p),
  removeHeroClass: (p) => ipcRenderer.invoke('mods:remove-class', p),
  installHeroSkill: (p) => ipcRenderer.invoke('mods:install-skill', p),
  updateHeroSkill: (p) => ipcRenderer.invoke('mods:update-skill', p),
  removeHeroSkill: (p) => ipcRenderer.invoke('mods:remove-skill', p),
  classData: () => ipcRenderer.invoke('mods:class-data'),
  updateSpecialization: (p) => ipcRenderer.invoke('mods:update-specialization', p),
  removeSpecialization: (p) => ipcRenderer.invoke('mods:remove-specialization', p),
  heroArtOf: (hero) => ipcRenderer.invoke('mods:hero-art', { hero }),
  pickHeroFile: (p) => ipcRenderer.invoke('mods:pick-hero-file', p),
  pickPicture: () => ipcRenderer.invoke('mods:pick-picture'),
  updateArtifact: (p) => ipcRenderer.invoke('mods:update-artifact', p),
  updateArtifactSet: (p) => ipcRenderer.invoke('mods:update-set', p),
  creatureUses: (p) => ipcRenderer.invoke('mods:creature-uses', p),
  removeCreature: (p) => ipcRenderer.invoke('mods:remove-creature', p),
  artifactUses: (p) => ipcRenderer.invoke('mods:artifact-uses', p),
  removeArtifact: (p) => ipcRenderer.invoke('mods:remove-artifact', p),
  removeArtifactSet: (p) => ipcRenderer.invoke('mods:remove-set', p),
  extensionStatus: () => ipcRenderer.invoke('mods:extension-status'),
  installExtension: () => ipcRenderer.invoke('mods:install-extension'),
  modTextures: (target) => ipcRenderer.invoke('mods:textures', target),
  recolorMod: (p) => ipcRenderer.invoke('mods:recolor', p),
  // Diagnostics for the fatal-error screen (renderer/parts/fatal.html). It shows up
  // when the renderer module died, so these two are all it can still call —
  // preload has its own context and survives.
  gpuReport: () => ipcRenderer.invoke('app:gpu-report'),
  openDevTools: () => ipcRenderer.invoke('app:open-devtools'),
  launchGame: () => ipcRenderer.invoke('app:launch-game'),
  qolGet: () => ipcRenderer.invoke('qol:get'),
  qolApply: (settings) => ipcRenderer.invoke('qol:apply', { settings }),
  gpuSoftware: () => ipcRenderer.invoke('app:gpu-software'),
  setGpuSoftware: (on) => ipcRenderer.invoke('app:set-gpu-software', { on }),
  idleAnimation: () => ipcRenderer.invoke('app:idle-animation'),
  setIdleAnimation: (mode) => ipcRenderer.invoke('app:set-idle-animation', { mode }),
  idleSkins: () => ipcRenderer.invoke('map:idle-skins'),
  fx: (uids) => ipcRenderer.invoke('map:fx', { uids }),
  // Push channel, not invoke: the main process decides when the folder moved.
  // The listener is wrapped so the renderer never sees the IpcRendererEvent.
  onExternalChange: (cb) => { ipcRenderer.on('map:external-change', (_e, c) => cb(c)); },
};

contextBridge.exposeInMainWorld('editor', api);
