// The config's rows: one per term the editor writes for us to add.
//
// A piece of the ONE translation unit — native/homm5-editor.c includes every
// piece in order, so everything included before this file is visible here and
// nothing after it is. Statics stay statics; nothing here is a module.

// ---------------------------------------------------------------------------
// Config: one row per term we add. Written by the editor, read here.
//
//   # comment
//   necromancy artifact 97 30        <- artifact 97 worn, +30% raised
//   energy set 2 150 97 98 99        <- any 2 of those three worn, +150 energy
//   necromancy skill 221 5           <- skill 221 held, +5% for each of its
//                                       four mastery levels
//
// Deliberately a flat text file: it is generated by one program and read by
// another, and when something does not work the first question is what it
// actually says.

/**
 * Which sum a row belongs to. One place in the executable per entry.
 *
 * `necromancy` is a HERO's — the engine asks about one hero and the row is
 * answered for that hero. `energy` is a PLAYER's, so its rows are answered for
 * every hero of theirs and added up, the way another Amplifier would be.
 * `tent_charges` is a hero's again, asked once when his first aid tent is built
 * for a battle, and so are the four beside it: `tent_healing` is points added to
 * what one use of the tent is worth, `tent_cleanse` levels added to the worst
 * effect it can lift off the stack it heals, `tent_health` percent added to the
 * machine's own hit points, and `tent_mana` charges given back per hundred
 * points of mana its owner spends. All four are the tent's, and three of them
 * are answered in one function — see docs/engineInternals/FIRST_AID_TENT.md.
 */
typedef enum {
  STAT_NECROMANCY = 0,
  STAT_ENERGY = 1,
  STAT_TENT_CHARGES = 2,
  STAT_TENT_HEALING = 3,
  STAT_TENT_HEALTH = 4,
  STAT_TENT_CLEANSE = 5,
  STAT_TENT_MANA = 6,
  STAT_COUNT = 7
} Stat;

static const char *const STAT_NAMES[STAT_COUNT] = {
  "necromancy", "energy", "tent_charges", "tent_healing", "tent_health",
  "tent_cleanse", "tent_mana",
};

/**
 * One term: while these artifacts are worn, add this much.
 *
 * A single artifact and a whole set are the same row with a different count.
 * The set is counted HERE rather than asked of the engine on purpose: the
 * hero's set accessor answers 0 for an effect of ours (the game draws the set
 * on the hero screen from data, which is a different reader), so a set that
 * only the executable can recognise would never combine. Counting our own
 * members through `CountEquipped` needs nothing of ours to be reachable, and
 * the threshold becomes our number instead of one compiled into an effect.
 */
typedef struct {
  int stat;
  int members[MAX_MEMBERS];
  int memberCount;
  int threshold; /**< pieces worn, at least this many */
  int amount;    /**< percentage points, or energy */
} Row;

static Row g_rows[MAX_ROWS];
static int g_rowCount = 0;

/**
 * One term a SKILL of ours adds: this much for each level of mastery held.
 *
 * Not a Row with different words — nothing is worn and nothing is counted. The
 * subject is a value of the `HeroSkill` enum the executable was not built with,
 * and the question we ask about it is the hero's own `GetSkillMastery`, so no
 * id of ours has to be reachable from the code. It enters the same sums a Row
 * does because it is asked in the same place: `necromancy` for the one hero,
 * `energy` for every hero of the player.
 */
typedef struct {
  int stat;
  int skill;
  int amountPerMastery;
} SkillRow;

#define MAX_SKILL_ROWS 32
static SkillRow g_skillRows[MAX_SKILL_ROWS];
static int g_skillRowCount = 0;

/**
 * Which sum a SPECIALIZATION row belongs to. One so far, and one place in the
 * executable behind it: the first aid tent's amount.
 */
typedef enum { SPEC_STAT_TENT = 0, SPEC_STAT_COUNT = 1 } SpecStat;

static const char *const SPEC_STAT_NAMES[SPEC_STAT_COUNT] = { "tent" };

/**
 * One term a specialization adds: while a hero holds this value, add this many
 * percent of the engine's own number for every level he has.
 *
 * Nothing is worn and nothing is counted, which is why it is not a Row with
 * different words. The subject is a value of the `HeroSpecialization` enum —
 * a number the executable has never heard of, since every shipped one is
 * compiled against a literal — and the question we ask about it is the engine's
 * own `HasSpecialization`, so no id of ours has to be reachable from the code.
 */
typedef struct {
  int stat;
  int specialization;
  int percentPerLevel;
} SpecRow;

#define MAX_SPEC_ROWS 16
static SpecRow g_specRows[MAX_SPEC_ROWS];
static int g_specRowCount = 0;

/**
 * The number of the ability that means "this creature is a dragon" —
 * `dragon-ability <n>`, one line.
 *
 * Not a term added to a sum like every row above it, and not a list of
 * creatures either: a creature says what it is in its OWN record, the way it
 * says it is undead, and we ask it. The one thing that cannot be worked out
 * here is which number the editor gave that ability when it built the mod — so
 * that number, and nothing else, is what the line carries. Move the ability and
 * the line moves with it.
 */
static int g_dragonAbility = 0;

static RaiseFn g_original = NULL;
static CostFn g_originalCost = NULL;
static PlayerFn g_originalRefill = NULL;
static PlayerFn g_originalRecalc = NULL;

/** Whether any row wants that sum — nothing is hooked for a stat with no rows. */
static int rows_for(int stat) {
  for (int i = 0; i < g_rowCount; i++) if (g_rows[i].stat == stat) return 1;
  for (int i = 0; i < g_skillRowCount; i++) if (g_skillRows[i].stat == stat) return 1;
  return 0;
}

/** Is this address inside the executable's code? A wrong slot is not called. */
static int points_at_code(void *fn);

