// The editor's own extension, loaded into the game.
//
// WHAT IT IS FOR. An artifact record carries six hero stats and nothing else.
// Everything a shipped artifact does beyond that is compiled into the
// executable against a specific id, so a new id gets none of it — see
// docs/ENGINE_INTERNALS.md. This adds our own terms to the engine's own
// arithmetic: it calls the original calculation, appends what our config says,
// and returns the sum. Nothing shipped changes behaviour.
//
// HOW IT GETS LOADED. Not by taking another library's name: `H5_Game_NCF.exe`
// is our copy already, and it names this file in its import table. So no file
// of the game's is touched, and turning the mod off is what it always was —
// launch the game's own executable instead.
//
// WHAT IT HOOKS, for now. `CNecromancy::RaisePercent` — one function, called
// once, that sums base + skill + perk + amplifiers + grail + pendant + set. Its
// last term is "count worn pieces of set 5, if at least 4 add a number from
// data"; ours is the same shape with our set and our number.
//
// ONE ADDRESS, AND ONLY ONE. The hero arrives as `this`, and the engine asks
// how many pieces of a set are worn through the hero's OWN vtable (+0x328), so
// that call needs no address at all — we make it the way the engine makes it,
// two instructions above where we cut in. The single address we do need is
// verified against the bytes we expect before anything is written.
//
// NO C RUNTIME. Only kernel32: this is injected into a 2007 executable, and a
// runtime that has to initialise is one more thing that can fail in a process
// that is not ours. Parsing and formatting are done by hand below; there is not
// much of either.

#include <windows.h>

// ---------------------------------------------------------------------------
// The build we know, as landmarks rather than constants.

/** `CNecromancy::RaisePercent`, RVA in the 3.1 build. Verified before use. */
#define RAISE_PERCENT_RVA 0x877850u
/** Its first five bytes: sub esp,8 / push ebx / push ebp. A whole number of
 *  instructions, which is why the detour is exactly this long. */
static const BYTE RAISE_PERCENT_HEAD[5] = { 0x83, 0xEC, 0x08, 0x53, 0x55 };
/**
 * `CNecromancy::RaiseCost` — what one creature costs in dark energy.
 *
 * Hooked only to watch, for now. The percentage says how many the engine will
 * OFFER; this says what each one is paid for, and which of the two is doing the
 * limiting is not something to reason about from the outside. Its prologue is
 * five pushes, so the detour is again a whole number of instructions.
 */
#define RAISE_COST_RVA 0x877270u
static const BYTE RAISE_COST_HEAD[5] = { 0x51, 0x53, 0x55, 0x56, 0x57 };

/** Where a hero hands over the artifacts it is WEARING. */
#define VT_WORN_ARTIFACTS 0x74u
/** `CountEquipped(collection, artifactId)`, and the bytes that say it is. */
#define COUNT_EQUIPPED_RVA 0x74c270u
static const BYTE COUNT_EQUIPPED_HEAD[5] = { 0x53, 0x8B, 0x19, 0x56, 0x57 };
/** Where a hero answers "how many pieces of set N am I wearing". */
#define VT_ARTIFACT_SET_COUNT 0x328u

#define DETOUR_LEN 5
#define MAX_ROWS 64

typedef int(__thiscall *SetCountFn)(void *hero, int effect);
typedef void *(__thiscall *WornFn)(void *hero);
typedef int(__thiscall *CountEquippedFn)(void *worn, int artifactId);
typedef int(__fastcall *RaiseFn)(void *hero);
typedef int(__fastcall *CostFn)(void *hero, int power);

static CountEquippedFn g_countEquipped = NULL;

// ---------------------------------------------------------------------------
// Config: one row per term we add. Written by the editor, read here.
//
//   # comment
//   necromancy set 11 3 15      <- set effect 11, at 3 pieces worn, +15
//
// Deliberately a flat text file: it is generated by one program and read by
// another, and when something does not work the first question is what it
// actually says.

/**
 * What a row is keyed on.
 *
 * `ROW_ARTIFACT` is the one to reach for. It asks the engine's own
 * `CountEquipped` about an artifact id — the same call the shipped
 * Necromancer's Pendant term makes, two instructions above where we cut in —
 * so there is nothing to get wrong and nothing that has to be reachable.
 * `ROW_SET` goes through the hero's set accessor, which is a different
 * question: the game draws an eleventh set and counts its pieces on the hero
 * screen, but the accessor answered 0 for it, so a set of ours may not be
 * reachable that way at all. Per-artifact rows do not care.
 */
typedef enum { ROW_ARTIFACT = 0, ROW_SET = 1 } RowKind;

typedef struct {
  RowKind kind;
  int id;        /**< an artifact id, or an ArtifactSetEffect value */
  int threshold; /**< pieces worn, at least this many */
  int amount;    /**< percentage points to add */
} Row;

static Row g_rows[MAX_ROWS];
static int g_rowCount = 0;

static RaiseFn g_original = NULL;
static CostFn g_originalCost = NULL;

// ---------------------------------------------------------------------------
// Small helpers, since there is no CRT.

static int str_eq_n(const char *a, const char *b, int n) {
  for (int i = 0; i < n; i++) if (a[i] != b[i]) return 0;
  return 1;
}

/** Append text to the log beside the DLL. Silent if it cannot. */
static void log_line(const char *text);

static void num_to_dec(int v, char *out, int *len) {
  char tmp[12];
  int n = 0, neg = v < 0;
  unsigned u = neg ? (unsigned)(-v) : (unsigned)v;
  if (!u) tmp[n++] = '0';
  while (u) { tmp[n++] = (char)('0' + u % 10); u /= 10; }
  int i = 0;
  if (neg) out[i++] = '-';
  while (n) out[i++] = tmp[--n];
  *len = i;
}

/** Read one decimal from `p`, advancing it. Returns 0 when there was none. */
static int read_int(const char **p, const char *end, int *out) {
  const char *s = *p;
  while (s < end && (*s == ' ' || *s == '\t')) s++;
  int neg = 0;
  if (s < end && (*s == '-' || *s == '+')) { neg = *s == '-'; s++; }
  if (s >= end || *s < '0' || *s > '9') return 0;
  int v = 0;
  while (s < end && *s >= '0' && *s <= '9') { v = v * 10 + (*s - '0'); s++; }
  *out = neg ? -v : v;
  *p = s;
  return 1;
}

// ---------------------------------------------------------------------------
// Where we live, and what sits beside us.

static WCHAR g_dir[MAX_PATH];

static void find_our_dir(HINSTANCE self) {
  DWORD n = GetModuleFileNameW(self, g_dir, MAX_PATH);
  while (n && g_dir[n - 1] != L'\\' && g_dir[n - 1] != L'/') n--;
  g_dir[n] = 0;
}

/** `<our folder>\name`, into `out`. */
static void beside_us(const WCHAR *name, WCHAR *out) {
  int i = 0;
  while (g_dir[i] && i < MAX_PATH - 1) { out[i] = g_dir[i]; i++; }
  int j = 0;
  while (name[j] && i < MAX_PATH - 1) out[i++] = name[j++];
  out[i] = 0;
}

static void log_line(const char *text) {
  WCHAR path[MAX_PATH];
  beside_us(L"homm5-editor.log", path);
  HANDLE h = CreateFileW(path, FILE_APPEND_DATA, FILE_SHARE_READ, NULL, OPEN_ALWAYS,
                         FILE_ATTRIBUTE_NORMAL, NULL);
  if (h == INVALID_HANDLE_VALUE) return;
  DWORD written = 0;
  int len = 0;
  while (text[len]) len++;
  WriteFile(h, text, (DWORD)len, &written, NULL);
  WriteFile(h, "\r\n", 2, &written, NULL);
  CloseHandle(h);
}

static void log_num(const char *prefix, int value) {
  char line[128];
  int i = 0;
  while (prefix[i] && i < 100) { line[i] = prefix[i]; i++; }
  int n = 0;
  num_to_dec(value, line + i, &n);
  line[i + n] = 0;
  log_line(line);
}

// ---------------------------------------------------------------------------
// Reading the config.

static void load_config(void) {
  WCHAR path[MAX_PATH];
  beside_us(L"homm5-editor-effects.txt", path);
  HANDLE h = CreateFileW(path, GENERIC_READ, FILE_SHARE_READ, NULL, OPEN_EXISTING,
                         FILE_ATTRIBUTE_NORMAL, NULL);
  if (h == INVALID_HANDLE_VALUE) { log_line("no config beside the dll - nothing to add"); return; }

  char buf[8192];
  DWORD got = 0;
  ReadFile(h, buf, sizeof(buf) - 1, &got, NULL);
  CloseHandle(h);
  buf[got] = 0;

  const char *p = buf, *end = buf + got;
  while (p < end) {
    const char *line = p;
    while (p < end && *p != '\n') p++;
    const char *stop = p;
    if (p < end) p++;
    while (line < stop && (*line == ' ' || *line == '\t')) line++;
    if (line >= stop || *line == '#') continue;

    //   necromancy artifact <id> <amount>
    //   necromancy set <effect> <threshold> <amount>
    Row r;
    const char *q;
    if (str_eq_n(line, "necromancy artifact ", 20)) {
      r.kind = ROW_ARTIFACT;
      r.threshold = 1;
      q = line + 20;
      if (!read_int(&q, stop, &r.id)) continue;
      if (!read_int(&q, stop, &r.amount)) continue;
    } else if (str_eq_n(line, "necromancy set ", 15)) {
      r.kind = ROW_SET;
      q = line + 15;
      if (!read_int(&q, stop, &r.id)) continue;
      if (!read_int(&q, stop, &r.threshold)) continue;
      if (!read_int(&q, stop, &r.amount)) continue;
    } else {
      continue;
    }
    if (g_rowCount < MAX_ROWS) g_rows[g_rowCount++] = r;
  }
  log_num("config rows: ", g_rowCount);
}

// ---------------------------------------------------------------------------
// The added term.

/**
 * How many calls still say what they saw.
 *
 * Bounded because this runs whenever the game wants the percentage and a log
 * that grows without end is its own problem — but the first few are worth
 * having: "the hook is installed" and "the hook adds something" are different
 * claims, and only the second one explains a number on screen.
 */
static int g_traceLeft = 24;

static int __fastcall raise_percent_hook(void *hero) {
  int total = g_original(hero);
  if (!hero) return total;
  void **vtable = *(void ***)hero;
  // The collection of what the hero is WEARING, fetched the way the engine
  // fetches it in this very function for the Necromancer's Pendant.
  void *worn = ((WornFn)vtable[VT_WORN_ARTIFACTS / 4])(hero);
  SetCountFn setCount = (SetCountFn)vtable[VT_ARTIFACT_SET_COUNT / 4];
  int added = 0;
  for (int i = 0; i < g_rowCount; i++) {
    int have = g_rows[i].kind == ROW_ARTIFACT
        ? (worn ? g_countEquipped(worn, g_rows[i].id) : 0)
        : setCount(hero, g_rows[i].id);
    if (g_traceLeft > 0) {
      log_num(g_rows[i].kind == ROW_ARTIFACT ? "  artifact " : "  set ", g_rows[i].id);
      log_num("    worn ", have);
    }
    if (have >= g_rows[i].threshold) added += g_rows[i].amount;
  }
  if (g_traceLeft > 0) {
    g_traceLeft--;
    log_num("raise: engine said ", total);
    log_num("       we add ", added);
  }
  return total + added;
}

/**
 * What one creature costs in dark energy. Watched, not changed.
 *
 * Logged because "the percentage went up and the number raised did not" has
 * more than one explanation, and they are indistinguishable from outside the
 * process. Here they are three numbers.
 */
static int g_costTraceLeft = 24;

static int __fastcall raise_cost_hook(void *hero, int power) {
  int cost = g_originalCost(hero, power);
  if (g_costTraceLeft > 0) {
    g_costTraceLeft--;
    log_num("cost: creature power ", power);
    log_num("      energy per one ", cost);
  }
  return cost;
}

// ---------------------------------------------------------------------------
// Installing it.

/**
 * Overwrite the first five bytes with a jump to us, and keep a trampoline that
 * runs those bytes and jumps back.
 *
 * The five are a whole number of instructions in this build, which is checked
 * before anything is written: a detour that splits an instruction corrupts the
 * function rather than replacing it, and the crash lands somewhere else
 * entirely.
 */
static void *detour(DWORD rva, const BYTE *head, void *hook, const char *what) {
  // The RVA, added to wherever the loader actually put the image — the game's
  // preferred base is 0x400000 but nothing guarantees it got that one.
  BYTE *target = (BYTE *)GetModuleHandleW(NULL) + rva;
  for (int i = 0; i < DETOUR_LEN; i++) {
    if (target[i] != head[i]) {
      char msg[96];
      int n = 0;
      while (what[n] && n < 60) { msg[n] = what[n]; n++; }
      const char *tail = ": the bytes are not the ones we know - not hooking";
      int j = 0;
      while (tail[j]) msg[n + j] = tail[j], j++;
      msg[n + j] = 0;
      log_line(msg);
      return NULL;
    }
  }

  BYTE *tramp = (BYTE *)VirtualAlloc(NULL, 32, MEM_COMMIT | MEM_RESERVE, PAGE_EXECUTE_READWRITE);
  if (!tramp) { log_line("no memory for the trampoline"); return NULL; }
  for (int i = 0; i < DETOUR_LEN; i++) tramp[i] = target[i];
  tramp[DETOUR_LEN] = 0xE9;
  *(DWORD *)(tramp + DETOUR_LEN + 1) =
      (DWORD)(target + DETOUR_LEN) - (DWORD)(tramp + DETOUR_LEN + 5);

  DWORD old = 0;
  if (!VirtualProtect(target, DETOUR_LEN, PAGE_EXECUTE_READWRITE, &old)) {
    log_line("could not make the code writable");
    return NULL;
  }
  target[0] = 0xE9;
  *(DWORD *)(target + 1) = (DWORD)hook - ((DWORD)target + 5);
  VirtualProtect(target, DETOUR_LEN, old, &old);
  FlushInstructionCache(GetCurrentProcess(), target, DETOUR_LEN);
  return tramp;
}

static int install_detour(void) {
  // Read by address, never written — but a wrong one would be CALLED with a
  // live object, so it is checked the same way as the ones we overwrite.
  BYTE *counter = (BYTE *)GetModuleHandleW(NULL) + COUNT_EQUIPPED_RVA;
  for (int i = 0; i < 5; i++) {
    if (counter[i] != COUNT_EQUIPPED_HEAD[i]) {
      log_line("the bytes at CountEquipped are not the ones we know - not hooking");
      return 0;
    }
  }
  g_countEquipped = (CountEquippedFn)counter;

  g_original = (RaiseFn)detour(RAISE_PERCENT_RVA, RAISE_PERCENT_HEAD, &raise_percent_hook, "raise percent");
  if (!g_original) return 0;
  // Watching only, and a failure here is not fatal: the percentage is the part
  // that has to work.
  g_originalCost = (CostFn)detour(RAISE_COST_RVA, RAISE_COST_HEAD, &raise_cost_hook, "raise cost");
  return 1;
}

BOOL WINAPI DllMain(HINSTANCE self, DWORD reason, LPVOID reserved) {
  (void)reserved;
  if (reason != DLL_PROCESS_ATTACH) return TRUE;
  DisableThreadLibraryCalls(self);
  find_our_dir(self);
  log_line("--- homm5-editor extension loaded");
  load_config();
  if (g_rowCount && install_detour()) log_line("necromancy hook installed");
  return TRUE;
}

/** So the import that loads us has something to name. */
__declspec(dllexport) int homm5_editor_present(void) { return 1; }
