// A set that reacts to something: the Lua half of an artifact set.
//
// The extension adds NUMBERS to the engine's own arithmetic — a percentage, a
// ceiling — because those live inside calculations no script can reach. What it
// cannot do is decide WHEN: "at the start of every day", "when this building is
// visited", "after that battle" are events, and the engine already hands events
// to Lua. So the two halves split along that line, and this file is the second
// one: the script a set carries, and how it reaches the game.
//
// HOW IT REACHES THE GAME. `scripts/advmap-startup.lua` ends with
// `doFile("/scripts/advmap-common.lua")`, and both are ordinary files under the
// data root, so a mod that carries its own copy runs code on EVERY adventure
// map — the game's own included. Measured, not assumed: see
// docs/NAMES_AND_SCRIPTING.md, where a probe answered both this and whether a
// trigger set here survives a map that sets its own (it does; triggers stack).
//
// WHAT IS GENERATED AND WHAT IS AUTHORED. The header is ours: the set's members
// as the constants a script names them by, and the helpers in the global file
// hide the walk over heroes. Everything else is the author's, verbatim — a
// script is a script, and what runs is what they wrote.

import type { ModArtifactSet } from './mod-model.ts';

/** Where a set's script goes inside the mod. */
export const SCRIPT_DIR = 'scripts/homm5-editor';
/** The game's global script, which we carry a copy of when there is anything to load. */
export const COMMON_SCRIPT = 'scripts/advmap-common.lua';

const EOL = '\r\n';

/** A Lua name from a file stem: what the generated symbols are prefixed with. */
export const symbolOf = (file: string): string => file.replace(/[^A-Za-z0-9_]/g, '_');

/**
 * What a set's script looks like before anybody has written anything.
 *
 * Not a nicety. Everything above the author's first line is knowledge they have
 * no way to have: that the members arrive as `<Set>_MEMBERS`, that the walk over
 * players is theirs to write, that `EditorHeroWearing` is the question to ask,
 * and — the one that decides whether ANY of it runs — that the file has to end
 * in a `Trigger` call. An empty editor asks for all four at once and answers
 * none; the set this was written from got them by being written by hand next to
 * the generator.
 *
 * Written ONCE, when the editor is opened on a set that has no script. The name
 * is right from the start because the stem is typed before the script is —
 * nothing here is ever rewritten afterwards, and a set that wants a second
 * behaviour at a different number of pieces gets a copy of the function.
 *
 * A day is the frame because it is the one every "while these are worn" effect
 * fits: the trigger stays hooked for the whole map and the CHECK is what changes
 * its mind, which is why nothing here ever unhooks anything (see
 * docs/NAMES_AND_SCRIPTING.md — the trigger is the WHEN, the condition inside is
 * the WHETHER).
 *
 * It lives beside the generator so the two cannot drift: the constant this
 * names is the constant `header()` writes.
 *
 * @param file    the set's file stem — the same one the header is built from
 * @param members how many pieces the set has, which is the count to start from
 */
export function starterScript(file: string, members: number): string {
  const name = symbolOf(file || 'MySet');
  return [
    `-- Runs on every adventure map, once a day. \`${name}_MEMBERS\` is written`,
    '-- for you in the head above; everything from here down is yours.',
    `function ${name}_NewDay()`,
    `	local x = ${Math.max(1, members || 1)};   -- pieces that have to be on`,
    '	for player = 1, 8 do',
    `		local hero = EditorHeroWearing(player, ${name}_MEMBERS, x);`,
    '		if hero then',
    '			-- Your code. `hero` is wearing them, `player` owns him.',
    '			-- e.g. RestoreDarkEnergy(player);',
    '		end;',
    '	end;',
    'end;',
    '',
    '-- Without this line nothing above ever runs.',
    `Trigger(NEW_DAY_TRIGGER, "${name}_NewDay");`,
    '',
    '-- A second behaviour at a different number of pieces is a copy of the',
    '-- function above with another x, and its own Trigger line.',
    '',
  ].join(EOL);
}

/**
 * The generated head of a set's script: its members, by the names a script uses.
 *
 * The ids are the constants `advmap-startup.lua` defines — the mod appends its
 * own artifacts to that list already, so a member of ours is as nameable as a
 * shipped one.
 */
function header(set: ModArtifactSet): string {
  const name = symbolOf(set.file);
  return [
    `-- ${set.name || set.effect} — generated by the editor. Do not edit this head;`,
    '-- it is rewritten whenever the set changes. The code below it is yours.',
    `${name}_MEMBERS = { ${set.artifacts.join(', ')} };`,
    '',
  ].join(EOL) + EOL;
}

/** One file per set that carries a script, plus nothing when none do. */
export function setScriptFiles(sets: readonly ModArtifactSet[]): { path: string; text: string }[] {
  return sets
    .filter((s) => s.script?.trim())
    .map((s) => ({
      path: `${SCRIPT_DIR}/${s.file}.lua`,
      text: header(s) + s.script!.replace(/\r?\n/g, EOL),
    }));
}

/**
 * The game's own `advmap-common.lua`, plus our library and one `doFile` per set.
 *
 * Appended rather than replaced: the 73 lines the game ships are what every
 * mission's script expects to find, and a mod that dropped them would break far
 * more than it added.
 */
export function patchCommonScript(shipped: string, sets: readonly ModArtifactSet[]): string {
  const files = setScriptFiles(sets);
  if (!files.length) return shipped;
  const block = [
    '',
    '-- --- homm5-editor ----------------------------------------------------------',
    '-- Helpers for artifact sets that carry a script, and the scripts themselves.',
    '-- Generated; the editor rewrites this block whenever the mod is built.',
    '',
    '-- How many of `members` this hero is WEARING. A piece in the backpack does',
    '-- not count: HasArtefact\'s third argument is the one the manuals omit.',
    'function EditorWornCount(hero, members)',
    '\tlocal worn = 0;',
    '\tfor index, id in members do',
    '\t\tif HasArtefact(hero, id, 1) then worn = worn + 1; end;',
    '\tend;',
    '\treturn worn;',
    'end;',
    '',
    '-- The first hero of this player wearing at least `count` of them, or nil.',
    'function EditorHeroWearing(player, members, count)',
    '\tlocal heroes = GetPlayerHeroes(player);',
    '\tif heroes == nil then return nil; end;',
    '\tfor index, hero in heroes do',
    '\t\tif EditorWornCount(hero, members) >= count then return hero; end;',
    '\tend;',
    '\treturn nil;',
    'end;',
    '',
    ...files.map((f) => `doFile("/${f.path}");`),
  ].join(EOL);
  return shipped.replace(/\s*$/, EOL) + block + EOL;
}
