// Pandora's Box: the behaviour, and the block a map carries.
//
// The split follows who owns what. The BEHAVIOUR — the question, the fight,
// the handing over — is one Lua file in the gameplay archive, versioned with
// the box itself: fix it once and every map is fixed. The DATA — which box
// holds what — is the map's, written into its script as a generated block
// between markers, the way an artifact set's script carries a generated head.
// The block starts with a doFile of the behaviour, which is safe exactly
// because a map that places boxes needs the archive anyway: without it there
// is no object to touch either.
//
// WHY NOT advmap-common.lua. The project mod already appends to its own copy
// of that file (artifact sets, skills), and two archives shipping the same
// path fight over it — whoever the game mounts last wins outright and the
// loser's scripts never load. The map's own script has no such fight: there
// is exactly one per map, and it is ours to generate into.
//
// THE FIGHT IS A LITERAL. StartCombat is variadic — creature type and count
// repeated, then two more arguments after them — and the engine's Lua 4 has
// no way to splice a data table into the middle of an argument list. The
// generated block writes each box's StartCombat out in full instead; the
// behaviour file only ever calls `box.fight(hero)`.

import { utf16 } from './mod-files.ts';
import type { ModFile } from './mod-files.ts';
import { PANDORA_RESOURCES } from './pandora-contents.ts';
import type { PandoraContents } from './pandora-contents.ts';

const EOL = '\r\n';

/** Where the behaviour lives inside the gameplay archive. */
export const PANDORA_SCRIPT = 'scripts/homm5-editor/pandora.lua';
/** The question a box asks, beside the behaviour. */
export const PANDORA_OPEN_TEXT = 'scripts/homm5-editor/pandora-open.txt';

/** The generated block's fences in a map script. Everything between them is
 *  rewritten on save; everything outside is the author's. */
export const PANDORA_BLOCK_BEGIN = '-- H5E pandora (generated) - everything to the end marker is rewritten on save';
export const PANDORA_BLOCK_END = '-- H5E pandora end';

/**
 * Where a box's message text was written, so the block can point at it.
 *
 * The behaviour shows a text REF, not a string — `MessageBox` takes a file —
 * so a box whose author typed a message needs that message written somewhere
 * first. Whoever generates the block (the editor's save, a test) writes the
 * files and answers this; a box with a message and no answer is refused rather
 * than quietly silenced.
 */
export type MessageRef = (box: PandoraContents) => string | undefined;

/**
 * The behaviour, shipped in the archive.
 *
 * Written in the shipped scripts' own idiom — semicolons, tabs, `for k, v in
 * table` — because that is the dialect proven to run in this engine. One
 * handler serves every box: the touch trigger hands over (heroName,
 * objectName), and the map's data table answers the rest.
 */
export function pandoraBehaviourLua(): string {
  return [
    "-- Pandora's Box - the behaviour. Shipped with the gameplay archive;",
    '-- maps that place boxes doFile this and fill H5E_PANDORA.',
    '-- Generated by the editor, rewritten with every archive build.',
    '',
    'H5E_PandoraHero = nil;',
    'H5E_PandoraObj = nil;',
    '',
    '-- Every step says its name: print lands in the game console, so a run',
    '-- that misbehaves reads as a story rather than a shrug.',
    'function H5E_PandoraTouch(heroName, objectName)',
    '\tif H5E_PANDORA == nil then return end;',
    '\tlocal box = H5E_PANDORA[objectName];',
    '\tif box == nil then return end;',
    '\tprint("H5E pandora: touched " .. objectName .. " by " .. heroName);',
    '\tH5E_PandoraHero = heroName;',
    '\tH5E_PandoraObj = objectName;',
    '\t-- An AI hero cannot answer a question box; it opens the box the way it',
    '\t-- opens everything else - without being asked.',
    '\tif IsAIPlayer(GetObjectOwner(heroName)) == true then',
    '\t\tprint("H5E pandora: AI opens without asking");',
    '\t\tH5E_PandoraOpen();',
    '\t\treturn',
    '\tend;',
    `\tQuestionBox("/${PANDORA_OPEN_TEXT}", "H5E_PandoraOpen", "H5E_PandoraLeave");`,
    'end;',
    '',
    'function H5E_PandoraLeave()',
    '\tH5E_PandoraObj = nil;',
    'end;',
    '',
    'function H5E_PandoraOpen()',
    '\tlocal box = H5E_PANDORA[H5E_PandoraObj];',
    '\tif box == nil then return end;',
    '\tlocal fight = nil;',
    '\tif H5E_PandoraFights ~= nil then fight = H5E_PandoraFights[H5E_PandoraObj]; end;',
    '\tif fight ~= nil then',
    '\t\tfight(H5E_PandoraHero);',
    '\telse',
    '\t\tH5E_PandoraGrant(H5E_PandoraHero, H5E_PandoraObj);',
    '\tend;',
    'end;',
    '',
    'function H5E_PandoraWon(hero, isWinner)',
    '\tif isWinner == true then',
    '\t\tH5E_PandoraGrant(H5E_PandoraHero, H5E_PandoraObj);',
    '\telse',
    '\t\tH5E_PandoraObj = nil;',
    '\tend;',
    'end;',
    '',
    'function H5E_PandoraGrant(hero, objectName)',
    '\tlocal box = H5E_PANDORA[objectName];',
    '\tif box == nil then return end;',
    '\tprint("H5E pandora: opening " .. objectName .. " for " .. hero);',
    '\tlocal player = GetObjectOwner(hero);',
    '\tif box.exp ~= nil then',
    '\t\tprint("H5E pandora: exp " .. box.exp);',
    '\t\tGiveExp(hero, box.exp);',
    '\tend;',
    '\tif box.res ~= nil then',
    '\t\tfor i, r in box.res do',
    '\t\t\tprint("H5E pandora: resource " .. r[1] .. " +" .. r[2]);',
    '\t\t\tSetPlayerResource(player, r[1], GetPlayerResource(player, r[1]) + r[2], hero);',
    '\t\tend;',
    '\tend;',
    '\tif box.artifacts ~= nil then',
    '\t\tfor i, a in box.artifacts do',
    '\t\t\tprint("H5E pandora: artifact " .. a);',
    '\t\t\tGiveArtefact(hero, a);',
    '\t\tend;',
    '\tend;',
    '\tif box.spells ~= nil then',
    '\t\tfor i, s in box.spells do',
    '\t\t\tprint("H5E pandora: spell " .. s);',
    '\t\t\tTeachHeroSpell(hero, s);',
    '\t\tend;',
    '\tend;',
    '\tif box.creatures ~= nil then',
    '\t\tfor i, c in box.creatures do',
    '\t\t\tprint("H5E pandora: creatures " .. c[1] .. " x" .. c[2]);',
    '\t\t\tAddHeroCreatures(hero, c[1], c[2]);',
    '\t\tend;',
    '\tend;',
    '\tif box.given ~= nil then MessageBox(box.given); end;',
    '\tH5E_PANDORA[objectName] = nil;',
    '\t-- The chest\'s own pickup can have eaten the object already (until the',
    '\t-- native gate lands); removing what is gone is an error worth avoiding.',
    '\tif IsObjectExists(objectName) then',
    '\t\tprint("H5E pandora: removing " .. objectName);',
    '\t\tRemoveObject(objectName);',
    '\telse',
    '\t\tprint("H5E pandora: " .. objectName .. " already gone");',
    '\tend;',
    '\tH5E_PandoraObj = nil;',
    'end;',
    '',
  ].join(EOL);
}

/** The behaviour and its texts, as files for the gameplay archive. */
export function pandoraBehaviourFiles(): ModFile[] {
  return [
    { path: PANDORA_SCRIPT, data: Buffer.from(pandoraBehaviourLua(), 'latin1') },
    { path: PANDORA_OPEN_TEXT, data: utf16('The box is sealed, and something waits inside. Open it?') },
  ];
}

// --- the map's block ---------------------------------------------------------

const luaNumber = (n: number): string => String(Math.round(n));

/** `gold` rides the same list as the mine resources: one loop grants them all. */
const RESOURCES: [keyof PandoraContents, string][] = [
  ...PANDORA_RESOURCES.map((r) => [r, r.toUpperCase()] as [keyof PandoraContents, string]),
  ['gold', 'GOLD'],
];

/**
 * One box's entry in the data table, its trigger line, and its fight.
 *
 * WRITTEN IN LUA 4'S OWN GRAMMAR, the hard-won parts of which are: inside a
 * table constructor the separator is the COMMA — a `;` there is "invalid
 * constructor syntax", and the whole DoString dies with every hook unbound
 * (found in the game's own error line, not by any linter). And the fight is a
 * NAMED function assigned into a dispatch table afterwards, not an anonymous
 * one inside the constructor — the dullest syntax the campaigns themselves
 * use, which is the syntax proven to parse.
 */
function boxLua(box: PandoraContents, messageRef: MessageRef | undefined): string[] {
  const fields: string[] = [];
  if (box.exp) fields.push(`\texp = ${luaNumber(box.exp)}`);
  const res = RESOURCES
    .filter(([key]) => box[key])
    .map(([key, constant]) => `{${constant}, ${luaNumber(box[key] as number)}}`);
  if (res.length) fields.push(`\tres = { ${res.join(', ')} }`);
  if (box.artifacts?.length) fields.push(`\tartifacts = { ${box.artifacts.join(', ')} }`);
  if (box.spells?.length) fields.push(`\tspells = { ${box.spells.join(', ')} }`);
  if (box.creatures?.length) {
    fields.push(`\tcreatures = { ${box.creatures.map((c) => `{${c.creature}, ${luaNumber(c.count)}}`).join(', ')} }`);
  }
  if (box.message) {
    const ref = messageRef?.(box);
    if (!ref) {
      throw new Error(`pandora: "${box.name}" has a message and nowhere to read it from —`
        + ' MessageBox takes a text file, so the message has to be written first');
    }
    fields.push(`\tgiven = "${ref}"`);
  }
  const out = [
    `H5E_PANDORA["${box.name}"] = {`,
    ...fields.map((f, i) => (i < fields.length - 1 ? `${f},` : f)),
    '};',
    `Trigger(OBJECT_TOUCH_TRIGGER, "${box.name}", "H5E_PandoraTouch");`,
  ];
  if (box.guards?.length) {
    const pairs = box.guards.map((g) => `${g.creature}, ${luaNumber(g.count)}`).join(', ');
    out.push(
      `function H5E_PandoraFight_${box.name}(hero)`,
      `\tStartCombat(hero, nil, ${box.guards.length}, ${pairs}, nil, "H5E_PandoraWon");`,
      'end;',
      `H5E_PandoraFights["${box.name}"] = H5E_PandoraFight_${box.name};`,
    );
  }
  return out;
}

/**
 * The generated block a map script carries, fences included.
 *
 * Boxes with no placement name are nobody's to trigger and are refused loudly
 * rather than silently skipped — a box that cannot be opened is a map bug.
 */
export function pandoraMapBlock(boxes: readonly PandoraContents[], messageRef?: MessageRef): string {
  for (const b of boxes) {
    if (!b.name) throw new Error('pandora: a box without a placement name cannot be triggered');
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(b.name)) {
      throw new Error(`pandora: "${b.name}" cannot name a box — the script quotes it, and the trigger`
        + ' looks it up as a map handle; letters, digits and underscores only');
    }
  }
  return [
    PANDORA_BLOCK_BEGIN,
    'H5E_PANDORA = {};',
    'H5E_PandoraFights = {};',
    ...boxes.flatMap((b) => boxLua(b, messageRef)),
    // The doFile comes LAST: a Trigger looks its handler up by name when it
    // fires, not when it binds, so the hooks survive even a doFile that dies —
    // where a doFile first would take the whole thread down with the hooks
    // still unbound, and every box would sit silent.
    `doFile("/${PANDORA_SCRIPT}");`,
    PANDORA_BLOCK_END,
    '',
  ].join(EOL);
}

/**
 * A map script with its pandora block brought up to date: the old block is
 * replaced in place, a script that never had one gains it at the TOP — before
 * anything of the author's runs, so their day-one code can already ask about
 * the boxes — and a map with no boxes left loses the block entirely.
 */
export function withPandoraBlock(
  script: string,
  boxes: readonly PandoraContents[],
  messageRef?: MessageRef,
): string {
  const begin = script.indexOf(PANDORA_BLOCK_BEGIN);
  const end = script.indexOf(PANDORA_BLOCK_END);
  const stripped = begin >= 0 && end > begin
    ? script.slice(0, begin) + script.slice(end + PANDORA_BLOCK_END.length).replace(/^\r?\n/, '')
    : script;
  if (!boxes.length) return stripped;
  return pandoraMapBlock(boxes, messageRef) + stripped;
}
