// Pandora's Box: the behaviour, and the block a map carries.
//
// The split follows who owns what. The BEHAVIOUR — the question, the fight,
// the handing over — is one Lua file in the gameplay archive, versioned with
// the box itself: fix it once and every map is fixed. The DATA — which box
// holds what — is the map's, written into its script as a generated block
// between markers, the way an artifact set's script carries a generated head.
// The block starts with a doFile of the behaviour, which is safe exactly
// because a map that places boxes needs the archive anyway: without it there
// is no object to touch either.
//
// WHY NOT advmap-common.lua. The project mod already appends to its own copy
// of that file (artifact sets, skills), and two archives shipping the same
// path fight over it — whoever the game mounts last wins outright and the
// loser's scripts never load. The map's own script has no such fight: there
// is exactly one per map, and it is ours to generate into.
//
// THE FIGHT IS A LITERAL. StartCombat is variadic — creature type and count
// repeated, then two more arguments after them — and the engine's Lua 4 has
// no way to splice a data table into the middle of an argument list. The
// generated block writes each box's StartCombat out in full instead; the
// behaviour file only ever calls `box.fight(hero)`.

import { utf16 } from './mod-files.ts';
import type { ModFile } from './mod-files.ts';
import { PANDORA_RESOURCES } from './pandora-contents.ts';
import type { PandoraContents } from './pandora-contents.ts';

const EOL = '\r\n';

/** Where the behaviour lives inside the gameplay archive. */
export const PANDORA_SCRIPT = 'scripts/homm5-editor/pandora.lua';
/** The question a box asks, beside the behaviour. */
export const PANDORA_OPEN_TEXT = 'scripts/homm5-editor/pandora-open.txt';
/** And what it says when the lid comes off and the guards are awake. */
export const PANDORA_GUARDS_TEXT = 'scripts/homm5-editor/pandora-guards.txt';

/** The generated block's fences in a map script. Everything between them is
 *  rewritten on save; everything outside is the author's. */
export const PANDORA_BLOCK_BEGIN = '-- H5E pandora (generated) - everything to the end marker is rewritten on save';
export const PANDORA_BLOCK_END = '-- H5E pandora end';

/**
 * Where a box's message text was written, so the block can point at it.
 *
 * The behaviour shows a text REF, not a string — `MessageBox` takes a file —
 * so a box whose author typed a message needs that message written somewhere
 * first. Whoever generates the block (the editor's save, a test) writes the
 * files and answers this; a box with a message and no answer is refused rather
 * than quietly silenced.
 */
export type MessageRef = (box: PandoraContents) => string | undefined;

/**
 * The two texts a box can point at, as the writer of the map answers for them.
 *
 * `said` is the author's own message, shown when the lid comes off; `report` is
 * the generated receipt of what was handed over, named in the game's words
 * (pandora-names.ts) and flown over the hero afterwards. Both are FILES because
 * both calls take a ref, and a caller that writes neither — a unit test, say —
 * simply gets a block without them.
 */
export interface PandoraRefs {
  said?: MessageRef;
  report?: MessageRef;
}

/**
 * The behaviour, shipped in the archive.
 *
 * Written in the shipped scripts' own idiom — semicolons, tabs, `for k, v in
 * table` — because that is the dialect proven to run in this engine. One
 * handler serves every box: the touch trigger hands over (heroName,
 * objectName), and the map's data table answers the rest.
 */
export function pandoraBehaviourLua(): string {
  return [
    "-- Pandora's Box - the behaviour. Shipped with the gameplay archive;",
    '-- maps that place boxes doFile this and fill H5E_PANDORA.',
    '-- Generated by the editor, rewritten with every archive build.',
    '',
    'H5E_PandoraHero = nil;',
    'H5E_PandoraObj = nil;',
    '',
    '-- Is this player somebody at the keyboard?',
    '--',
    '-- THE ONLY QUESTION THAT TELLS THEM APART. GetCurrentPlayer is the player',
    "-- whose TURN it is, not the one watching -- the shipped scripts spin",
    '-- `while GetCurrentPlayer() ~= PLAYER_2 do sleep(1); end` on it, which only',
    '-- makes sense that way round. So on the AI\'s own turn it equals the AI, and',
    '-- a gate built on it alone let the computer\'s box speak on our screen.',
    '--',
    '-- IsAIPlayer is undocumented and nothing shipped calls it, so its answer',
    '-- could be a boolean, a number or nil. Every shape is read here rather than',
    '-- guessed at: the wrong guess is silent in one direction (the AI keeps',
    '-- talking) and maddening in the other (the box never asks anybody).',
    'function H5E_PandoraIsHuman(player)',
    '\tlocal ai = IsAIPlayer(player);',
    '\tif ai == nil or ai == false or ai == 0 then return true; end;',
    '\treturn false;',
    'end;',
    '',
    '-- Every step says its name: print lands in the game console, so a run',
    '-- that misbehaves reads as a story rather than a shrug.',
    'function H5E_PandoraTouch(heroName, objectName)',
    '\tif H5E_PANDORA == nil then return end;',
    '\tlocal box = H5E_PANDORA[objectName];',
    '\tif box == nil then return end;',
    '\tprint("H5E pandora: touched " .. objectName .. " by " .. heroName);',
    '\tH5E_PandoraHero = heroName;',
    '\tH5E_PandoraObj = objectName;',
    '\t-- WHO IS ASKED, and it is not whoever happens to be watching.',
    '\t--',
    '\t-- A question box and a message box are shown to the SCREEN, not to a',
    '\t-- player: the script runs once and the popup lands wherever it lands. On',
    '\t-- a two-sided map that read as the OPPONENT opening a box - his reward',
    '\t-- announced to somebody who did not touch it. So the box speaks only for',
    '\t-- a human, and only on his own turn; an AI - or the other side of a',
    '\t-- hotseat - opens it in silence and gets everything just the same.',
    '\tlocal player = GetObjectOwner(heroName);',
    '\tif H5E_PandoraIsHuman(player) ~= true or player ~= GetCurrentPlayer() then',
    '\t\tprint("H5E pandora: opened without asking - not the watching player");',
    '\t\tH5E_PandoraOpen();',
    '\t\treturn',
    '\tend;',
    `\tQuestionBox("/${PANDORA_OPEN_TEXT}", "H5E_PandoraOpen", "H5E_PandoraLeave");`,
    'end;',
    '',
    'function H5E_PandoraLeave()',
    '\tH5E_PandoraObj = nil;',
    'end;',
    '',
    'function H5E_PandoraOpen()',
    '\tlocal box = H5E_PANDORA[H5E_PandoraObj];',
    '\tif box == nil then return end;',
    '\tlocal fight = nil;',
    '\tif H5E_PandoraFights ~= nil then fight = H5E_PandoraFights[H5E_PandoraObj]; end;',
    '\t-- THE BOX SPEAKS WHEN IT OPENS, not when the dust settles. The author\'s',
    '\t-- words are what is written on the lid, so they belong between "yes" and',
    '\t-- whatever comes out - a message that arrives after the battle reads as a',
    '\t-- reward slip, and for a guarded box it arrives minutes late.',
    '\tlocal player = GetObjectOwner(H5E_PandoraHero);',
    '\tlocal speaks = H5E_PandoraIsHuman(player) == true and player == GetCurrentPlayer();',
    '\tif box.said ~= nil and speaks == true then MessageBox(box.said); end;',
    '\tif fight ~= nil then',
    '\t\t-- And the box has the last word before the fight, the way Heroes III',
    '\t\t-- taunted whoever opened one. Ours, not a quotation.',
    `\t\tif speaks == true then MessageBox("/${PANDORA_GUARDS_TEXT}"); end;`,
    '\t\tfight(H5E_PandoraHero);',
    '\telse',
    '\t\tH5E_PandoraGrant(H5E_PandoraHero, H5E_PandoraObj);',
    '\tend;',
    'end;',
    '',
    'function H5E_PandoraWon(hero, isWinner)',
    '\tif isWinner == true then',
    '\t\tH5E_PandoraGrant(H5E_PandoraHero, H5E_PandoraObj);',
    '\telse',
    '\t\tH5E_PandoraObj = nil;',
    '\tend;',
    'end;',
    '',
    'function H5E_PandoraGrant(hero, objectName)',
    '\tlocal box = H5E_PANDORA[objectName];',
    '\tif box == nil then return end;',
    '\tprint("H5E pandora: opening " .. objectName .. " for " .. hero);',
    '\tlocal player = GetObjectOwner(hero);',
    '\tif box.exp ~= nil then',
    '\t\tprint("H5E pandora: exp " .. box.exp);',
    '\t\tGiveExp(hero, box.exp);',
    '\tend;',
    '\tif box.res ~= nil then',
    '\t\tfor i, r in box.res do',
    '\t\t\tprint("H5E pandora: resource " .. r[1] .. " +" .. r[2]);',
    '\t\t\tSetPlayerResource(player, r[1], GetPlayerResource(player, r[1]) + r[2], hero);',
    '\t\tend;',
    '\tend;',
    '\tif box.artifacts ~= nil then',
    '\t\tfor i, a in box.artifacts do',
    '\t\t\tprint("H5E pandora: artifact " .. a);',
    '\t\t\tGiveArtefact(hero, a);',
    '\t\tend;',
    '\tend;',
    '\tif box.spells ~= nil then',
    '\t\tfor i, s in box.spells do',
    '\t\t\tprint("H5E pandora: spell " .. s);',
    '\t\t\tTeachHeroSpell(hero, s);',
    '\t\tend;',
    '\tend;',
    '\tif box.creatures ~= nil then',
    '\t\tfor i, c in box.creatures do',
    '\t\t\tprint("H5E pandora: creatures " .. c[1] .. " x" .. c[2]);',
    '\t\t\tAddHeroCreatures(hero, c[1], c[2]);',
    '\t\tend;',
    '\tend;',
    '\t-- AND THE RECEIPT, in the game\'s own idiom: a flying sign over the hero,',
    '\t-- naming what he just got. Two of the eight kinds of content move a number',
    '\t-- in the HUD and nothing else, and a play-through read both as boxes that',
    '\t-- did nothing - a silent reward and a broken one look alike from outside.',
    '\t--',
    '\t-- ShowFlyingSign TAKES A PLAYER, which is the whole reason it is the right',
    '\t-- call here: the engine shows it to that player and to nobody else, so the',
    '\t-- computer\'s receipt cannot land on our screen the way its message did.',
    '\t-- The names in it are the game\'s own, written into the file at save time -',
    '\t-- Lua has no way to turn SPELL_IMPLOSION into what the spellbook calls it.',
    '\t--',
    '\t-- GetObjectOwner is asked again rather than carried: a fight sits between',
    '\t-- the two, and the hero can have changed hands or died in it.',
    '\tlocal owner = GetObjectOwner(hero);',
    '\tif box.report ~= nil then',
    '\t\tShowFlyingSign(box.report, hero, owner, 6);',
    '\tend;',
    '\tH5E_PANDORA[objectName] = nil;',
    '\t-- The chest\'s own pickup can have eaten the object already (until the',
    '\t-- native gate lands); removing what is gone is an error worth avoiding.',
    '\tif IsObjectExists(objectName) then',
    '\t\tprint("H5E pandora: removing " .. objectName);',
    '\t\tRemoveObject(objectName);',
    '\telse',
    '\t\tprint("H5E pandora: " .. objectName .. " already gone");',
    '\tend;',
    '\tH5E_PandoraObj = nil;',
    'end;',
    '',
  ].join(EOL);
}

/** The behaviour and its texts, as files for the gameplay archive. */
export function pandoraBehaviourFiles(): ModFile[] {
  return [
    { path: PANDORA_SCRIPT, data: Buffer.from(pandoraBehaviourLua(), 'latin1') },
    { path: PANDORA_OPEN_TEXT, data: utf16('The box is sealed, and something waits inside. Open it?') },
    { path: PANDORA_GUARDS_TEXT, data: utf16('Too late for second thoughts — the lid is off,'
      + ' and what was locked in is looking at you. Defend yourself!') },
  ];
}

// --- the map's block ---------------------------------------------------------

const luaNumber = (n: number): string => String(Math.round(n));

/** `gold` rides the same list as the mine resources: one loop grants them all. */
const RESOURCES: [keyof PandoraContents, string][] = [
  ...PANDORA_RESOURCES.map((r) => [r, r.toUpperCase()] as [keyof PandoraContents, string]),
  ['gold', 'GOLD'],
];

/**
 * An id as LUA must see it: a number stays a number, and a name gets the
 * prefix the engine's own globals carry.
 *
 * WHY THIS EXISTS. The game declares its ids as globals in
 * `scripts/advmap-startup.lua` — `ARTIFACT_BOOTS_OF_SPEED = 24`,
 * `SPELL_FIREBALL`, `CREATURE_PEASANT`. The REFERENCE TABLES key on the bare
 * name (`BOOTS_OF_SPEED`), and that is what an author's list is built from —
 * so a box written straight out of a table asked Lua for a global that does
 * not exist. What the game says about that is not an error but a warning:
 *
 *     [Script warning!] Value was NIL when getting global with name 'BOOTS_OF_SPEED'
 *
 * and the box then handed over `nil`, which `GiveArtefact` takes without
 * complaining. Six red lines and no artifacts. Prefixing here rather than at
 * the callers is deliberate: every list that reaches this file comes from a
 * table somewhere, and one place to be right is better than four.
 */
const luaId = (prefix: string) => (id: string | number): string => {
  if (typeof id === 'number') return String(id);
  const name = id.trim();
  if (/^\d+$/.test(name)) return name;
  return name.startsWith(prefix) ? name : prefix + name;
};

/**
 * One box's entry in the data table, its trigger line, and its fight.
 *
 * WRITTEN IN LUA 4'S OWN GRAMMAR, the hard-won parts of which are: inside a
 * table constructor the separator is the COMMA — a `;` there is "invalid
 * constructor syntax", and the whole DoString dies with every hook unbound
 * (found in the game's own error line, not by any linter). And the fight is a
 * NAMED function assigned into a dispatch table afterwards, not an anonymous
 * one inside the constructor — the dullest syntax the campaigns themselves
 * use, which is the syntax proven to parse.
 */
function boxLua(box: PandoraContents, refs: PandoraRefs | undefined): string[] {
  const fields: string[] = [];
  if (box.exp) fields.push(`\texp = ${luaNumber(box.exp)}`);
  const res = RESOURCES
    .filter(([key]) => box[key])
    .map(([key, constant]) => `{${constant}, ${luaNumber(box[key] as number)}}`);
  if (res.length) fields.push(`\tres = { ${res.join(', ')} }`);
  if (box.artifacts?.length) fields.push(`\tartifacts = { ${box.artifacts.map(luaId('ARTIFACT_')).join(', ')} }`);
  if (box.spells?.length) fields.push(`\tspells = { ${box.spells.map(luaId('SPELL_')).join(', ')} }`);
  if (box.creatures?.length) {
    fields.push(`\tcreatures = { ${box.creatures
      .map((c) => `{${luaId('CREATURE_')(c.creature)}, ${luaNumber(c.count)}}`).join(', ')} }`);
  }
  if (box.message) {
    const ref = refs?.said?.(box);
    if (!ref) {
      throw new Error(`pandora: "${box.name}" has a message and nowhere to read it from —`
        + ' MessageBox takes a text file, so the message has to be written first');
    }
    fields.push(`\tsaid = "${ref}"`);
  }
  // The receipt, when there is something to report: a box that only speaks has
  // nothing to hand over, and a caller that writes no texts answers nothing.
  const report = refs?.report?.(box);
  if (report) fields.push(`\treport = "${report}"`);
  const out = [
    `H5E_PANDORA["${box.name}"] = {`,
    ...fields.map((f, i) => (i < fields.length - 1 ? `${f},` : f)),
    '};',
    `Trigger(OBJECT_TOUCH_TRIGGER, "${box.name}", "H5E_PandoraTouch");`,
  ];
  if (box.guards?.length) {
    const pairs = box.guards
      .map((g) => `${luaId('CREATURE_')(g.creature)}, ${luaNumber(g.count)}`).join(', ');
    out.push(
      `function H5E_PandoraFight_${box.name}(hero)`,
      `\tStartCombat(hero, nil, ${box.guards.length}, ${pairs}, nil, "H5E_PandoraWon");`,
      'end;',
      `H5E_PandoraFights["${box.name}"] = H5E_PandoraFight_${box.name};`,
    );
  }
  return out;
}

/**
 * The generated block a map script carries, fences included.
 *
 * Boxes with no placement name are nobody's to trigger and are refused loudly
 * rather than silently skipped — a box that cannot be opened is a map bug.
 */
export function pandoraMapBlock(boxes: readonly PandoraContents[], refs?: PandoraRefs): string {
  for (const b of boxes) {
    if (!b.name) throw new Error('pandora: a box without a placement name cannot be triggered');
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(b.name)) {
      throw new Error(`pandora: "${b.name}" cannot name a box — the script quotes it, and the trigger`
        + ' looks it up as a map handle; letters, digits and underscores only');
    }
  }
  return [
    PANDORA_BLOCK_BEGIN,
    'H5E_PANDORA = {};',
    'H5E_PandoraFights = {};',
    ...boxes.flatMap((b) => boxLua(b, refs)),
    // The doFile comes LAST: a Trigger looks its handler up by name when it
    // fires, not when it binds, so the hooks survive even a doFile that dies —
    // where a doFile first would take the whole thread down with the hooks
    // still unbound, and every box would sit silent.
    `doFile("/${PANDORA_SCRIPT}");`,
    PANDORA_BLOCK_END,
    '',
  ].join(EOL);
}

/**
 * A map script with its pandora block brought up to date: the old block is
 * replaced in place, a script that never had one gains it at the TOP — before
 * anything of the author's runs, so their day-one code can already ask about
 * the boxes — and a map with no boxes left loses the block entirely.
 */
export function withPandoraBlock(
  script: string,
  boxes: readonly PandoraContents[],
  refs?: PandoraRefs,
): string {
  const begin = script.indexOf(PANDORA_BLOCK_BEGIN);
  const end = script.indexOf(PANDORA_BLOCK_END);
  const stripped = begin >= 0 && end > begin
    ? script.slice(0, begin) + script.slice(end + PANDORA_BLOCK_END.length).replace(/^\r?\n/, '')
    : script;
  if (!boxes.length) return stripped;
  return pandoraMapBlock(boxes, refs) + stripped;
}
