// The Lua half of a skill of ours — on the adventure map, and inside a battle.
//
// A skill's record gives it a name, an icon and a place in the tree; the native
// extension gives it a number inside a sum the engine computes. Between those
// two there is a third kind of skill, and the tent branch has one: a perk whose
// whole content is "after a battle, put back what the battle destroyed". That is
// an EVENT, and events are what the engine hands to Lua already.
//
// TWO FILES, BECAUSE A BATTLE IS ANOTHER WORLD. The game runs two Lua contexts
// with two different function tables — the adventure map's, and the battle's
// (`docs/EXE_LUA_REGISTRY.md`, tables 1-2 against table 3). Neither can see the
// other's calls, and what they share is `SetGameVar`/`GetGameVar`: each context
// registers its own pair, over the same store. So a skill that has to know
// something a battle knows writes it down in the battle and reads it back on the
// map, and this file gives it one file per side to write that in.
//
// HOW EACH SIDE IS REACHED. Both are the same trick, and both were measured
// rather than assumed (docs/NAMES_AND_SCRIPTING.md):
//
//   the map     `scripts/advmap-startup.lua` ends with a doFile of
//               `advmap-common.lua`, so a mod carrying its own copy of the
//               latter runs code on every adventure map.
//   the battle  `scripts/combat-startup.lua` BEGINS with a doFile of
//               `combat-common.lua` and then declares the empty hooks a combat
//               script overrides. Ours cannot go in `combat-common.lua`, then:
//               it would be overwritten by those declarations a moment later.
//               It goes at the END of our copy of `combat-startup.lua`.
//
// AND OURS DECLARES NOTHING THE GAME DECLARES. The block appended to the combat
// startup is straight-line code, not a redefinition of `AttackerWarMachineDeath`
// or any other hook: by the time it runs the battle exists and can simply be
// asked what is in it. Overriding a hook would work — no shipped script defines
// those two — but it would put our name on a global the game owns, and for
// nothing: we do not need to be told when the tent dies, only whether it was
// there when the battle began.

import type { ModHeroSkill } from './hero-skills.ts';
import { SCRIPT_DIR, symbolOf } from './artifact-scripts.ts';

/** The game's global battle script, whose tail we carry a copy of. */
export const COMBAT_STARTUP = 'scripts/combat-startup.lua';

/** Which of the game's two Lua contexts a script belongs to. */
export type Side = 'map' | 'combat';

const EOL = '\r\n';

/** The file stem a skill's scripts are named by: `HERO_SKILL_SPARE_KIT` -> `SPARE_KIT`. */
export const skillStem = (skill: ModHeroSkill): string =>
  symbolOf(skill.id.replace(/^HERO_SKILL_/, '')) || symbolOf(skill.id);

/** Where a skill's two scripts go inside the mod. */
export const skillScriptPath = (skill: ModHeroSkill, side: Side): string =>
  `${SCRIPT_DIR}/${skillStem(skill)}${side === 'combat' ? '-combat' : ''}.lua`;

/**
 * The generated head of a skill's script: what the author would otherwise have
 * to look up.
 *
 * The skill's own id, because `HasHeroSkill` takes a number and the number is
 * assigned by the build — a script naming it by hand goes wrong the day another
 * skill is added before it. And, on the battle side, the war machine types: the
 * adventure startup declares neither, and a bare `3` in a script is a puzzle
 * for whoever reads it next.
 */
function header(skill: ModHeroSkill): string {
  return [
    // ASCII, deliberately: these files are written latin1 because the engine
    // reads them byte by byte, and a dash of ours came out as a hole.
    `-- ${skill.id} - generated by the editor. Do not edit this head; it is`,
    '-- rewritten whenever the mod is built. The code below it is yours.',
    `${skill.id} = ${skill.number};`,
    // Neither context declares these. The adventure startup names every skill
    // and every artifact and stops there; the battle one names UNIT types
    // (HERO, CREATURE, WAR_MACHINE) and not the machines themselves. The
    // numbers are types.xml's own WarMachineType map.
    'WAR_MACHINE_BALLISTA = 1;',
    'WAR_MACHINE_CATAPULT = 2;',
    'WAR_MACHINE_FIRST_AID_TENT = 3;',
    'WAR_MACHINE_AMMO_CART = 4;',
  ].join(EOL) + EOL + EOL;
}

/**
 * What a side opens on when the skill has nothing written for it yet.
 *
 * Not decoration: everything above the author's first line is knowledge an empty
 * editor cannot give them — that the id is declared for them in the head, that a
 * function nothing hooks to a trigger never runs, and, on the battle side, that
 * there is no hook to write at all because the file itself runs once when the
 * battle is built.
 *
 * WHICH event is not ours to choose, so the map starter shows the shapes and
 * commits to none. It is a starting point, not a template the build knows about.
 */
export function skillStarter(id: string, side: Side): string {
  const name = symbolOf((id || 'HERO_SKILL_MINE').replace(/^HERO_SKILL_/, '')) || 'Skill';
  if (side === 'combat') {
    return [
      '-- Runs ONCE, when the battle has been built and before it is fought.',
      '-- Straight-line code: the game\'s own hooks (AttackerWarMachineDeath and',
      '-- the rest) stay the game\'s. What this context knows and the map does not',
      '-- is what is actually in the battle; what crosses back is a game variable.',
      'local hero = GetAttackerHero();',
      'if hero ~= nil then',
      '\t-- Your code. `GetHeroName(hero)` is the name the map knows him by.',
      `\t-- SetGameVar("h5e.${name}."..GetHeroName(hero), "1");`,
      'end;',
      '',
    ].join(EOL);
  }
  return [
    `-- \`${id || 'HERO_SKILL_MINE'}\` is declared for you in the head above.`,
    '-- Everything from here down is yours.',
    `function ${name}_Happened(combatIndex)`,
    '\tlocal hero = GetSavedCombatArmyHero(combatIndex, 1);',
    `\tif hero ~= nil and HasHeroSkill(hero, ${id || 'HERO_SKILL_MINE'}) then`,
    '\t\t-- Your code. `hero` holds this skill.',
    '\tend;',
    'end;',
    '',
    '-- Nothing above runs until it is hooked to an event, and WHICH event is',
    '-- yours to pick. Uncomment one, or write another:',
    `-- Trigger(COMBAT_RESULTS_TRIGGER, "${name}_Happened");`,
    `-- Trigger(NEW_DAY_TRIGGER, "${name}_Happened");`,
    '',
  ].join(EOL);
}

/** One file per side a skill carries a script for. */
export function skillScriptFiles(skills: readonly ModHeroSkill[]): { path: string; text: string }[] {
  const out: { path: string; text: string }[] = [];
  for (const s of skills) {
    for (const side of ['map', 'combat'] as Side[]) {
      const body = side === 'map' ? s.script : s.combatScript;
      if (!body?.trim()) continue;
      out.push({
        path: skillScriptPath(s, side),
        text: header(s) + body.replace(/\r?\n/g, EOL),
      });
    }
  }
  return out;
}

/** The adventure-side scripts, which `advmap-common.lua` loads. */
export const skillMapScripts = (skills: readonly ModHeroSkill[]): string[] =>
  skills.filter((s) => s.script?.trim()).map((s) => skillScriptPath(s, 'map'));

/** The battle-side ones, which our copy of `combat-startup.lua` loads. */
export const skillCombatScripts = (skills: readonly ModHeroSkill[]): string[] =>
  skills.filter((s) => s.combatScript?.trim()).map((s) => skillScriptPath(s, 'combat'));

/**
 * The game's `combat-startup.lua` with a doFile per battle script of ours.
 *
 * Appended, never replaced: those 250 lines are the vocabulary every combat
 * script in the game is written against (`IsWarMachine`, `GetAttackerHero`, the
 * death hooks), and a mod that dropped them would break every scripted battle
 * the game ships. The tail is the only safe place — before the declarations our
 * code would be there, and gone.
 */
export function patchCombatStartup(shipped: string, skills: readonly ModHeroSkill[]): string {
  // As SHORT as it can be. The engine compiles this file as one chunk and the
  // shipped text is already 7894 bytes; how much more it will take is not
  // written down anywhere, so ours is one comment and one line — everything else
  // lives behind the doFile, where its size is its own business.
  const block = ['', '-- homm5-editor', `doFile("/${COMBAT_RUNTIME}");`].join(EOL);
  return shipped.replace(/\s*$/, EOL) + block + EOL;
}

/**
 * Where our battle code lives, and why it is not in `combat-startup.lua` itself.
 *
 * THE ENGINE RUNS THAT FILE AS ONE CHUNK. It reads the whole thing and hands the
 * text to the script host in a single call — so the file is compiled as a unit,
 * and anything wrong anywhere in it takes down EVERY declaration it makes:
 * `IsAttacker`, `UnitDeath`, the aliases, all of them. Which is the file every
 * combat script in the game is written against.
 *
 * That is not a theory. With our block appended, a battle answered that it had
 * NONE of those names — not ours, and not the game's own either (measured
 * 2026-08-03, four battles: `what the battle has:` and nothing after it). A mod
 * was quietly breaking the game's own battle scripting, and it looked exactly
 * like "our perk does not work".
 *
 * So the copy we carry differs from the shipped file by ONE LINE, and everything
 * of ours is a file of its own: a separate `doFile` is a separate chunk, and a
 * mistake in ours can only cost ours.
 */
export const COMBAT_RUNTIME = `${SCRIPT_DIR}/combat.lua`;

/** That file: the trigger runtime, then a doFile per battle script of ours. */
export function combatRuntimeFile(skills: readonly ModHeroSkill[]): { path: string; text: string } {
  return {
    path: COMBAT_RUNTIME,
    text: [
      '-- Generated by the editor; rewritten whenever the mod is built.',
      '-- Loaded from the tail of combat-startup.lua, as its own chunk.',
      '',
      ...COMBAT_TRIGGER_RUNTIME,
      '',
      ...skillCombatScripts(skills).map((f) => `doFile("/${f}");`),
      '',
    ].join(EOL),
  };
}

/**
 * Triggers inside a battle — the vocabulary, in Lua, because it costs nothing
 * there and an argument read from Lua costs the engine's own parser.
 *
 * WHO CALLS WHOM. The extension composes a line of source and hands it to the
 * battle's script host — which is exactly how the engine runs its own
 * `DoPrepare()` and `UnitMove("%s")` — so arguments are free in that direction:
 * they are text. `H5EFire` is the one name it calls, and everything above it is
 * ordinary Lua a script can read.
 *
 * WHY REGISTRATION IS NOT NATIVE. `H5ESetCombatTrigger` could have been a
 * function of ours in the battle's table, but a native function that RECEIVES a
 * number and a string has to go through the engine's argument parser
 * (`0xa454d0`) and build the two heap strings it checks against — a job of its
 * own, and one whose mistakes crash a battle. Here the same API is fifteen lines
 * that cannot crash anything, and the native side keeps the one shape it has
 * proved: compose a line, run it.
 *
 * HANDLERS STACK, like the adventure map's triggers do — several perks may want
 * the same moment, and the one that registered second must not silence the
 * first.
 *
 * PLAIN LANGUAGE ONLY, and this was checked rather than assumed. The game is
 * Lua 4 (`pragmas are no longer supported`, the tag-method names `getglobal` and
 * `settable`) and it registers NONE of the standard library: `tinsert`, `getn`,
 * `type`, `tostring` — not one of those names is in the executable. What a
 * script has is the language and the game's own 306 functions. So a handler is
 * a FUNCTION rather than the name of one, because resolving a name would need
 * the very library that is not there.
 */
export const COMBAT_TRIGGER_RUNTIME = [
  '-- Triggers inside a battle. `H5EFire` is called by the extension; everything',
  '-- else here is for scripts to use. Lua 4 with no standard library, so the',
  '-- list keeps its own count and a handler is a function, not a name.',
  'H5E_COMBAT_STARTED = 1;',
  'H5E_HERO_MANA_CHANGED = 2;',
  'H5E_COMBAT_TRIGGERS = {};',
  '',
  'function H5ESetCombatTrigger(kind, handler)',
  '\tlocal list = H5E_COMBAT_TRIGGERS[kind];',
  '\tif list == nil then',
  '\t\tlist = { count = 0 };',
  '\t\tH5E_COMBAT_TRIGGERS[kind] = list;',
  '\tend;',
  '\tlist.count = list.count + 1;',
  '\tlist[list.count] = handler;',
  'end;',
  '',
  '-- Called by the extension, once per event.',
  'function H5EFire(kind, a, b, c)',
  '\tlocal list = H5E_COMBAT_TRIGGERS[kind];',
  // NO EARLY `return`, and it is not a matter of taste: Lua 4 refuses one that
  // is not the last statement of its block, and the file does not compile. It
  // cost this whole investigation — and, while our code sat inside
  // combat-startup.lua, it took the GAME's own battle declarations down with it.
  '\tif list ~= nil then',
  '\t\tlocal i = 1;',
  '\t\twhile i <= list.count do',
  '\t\t\tlocal handler = list[i];',
  '\t\t\tif handler ~= nil then handler(a, b, c); end;',
  '\t\t\ti = i + 1;',
  '\t\tend;',
  '\tend;',
  'end;',
];
