// Build the renderer: assemble the page, then bundle the code.
//
//   node tools/build-renderer.ts [--watch]
//
// Two outputs, both generated and both gitignored — renderer/index.html from
// renderer/page.html plus renderer/parts/, and renderer/app.js from
// renderer/app.ts. A script rather than a line of flags in package.json because
// four callers need the SAME build: `npm start`, `npm run harness`,
// `npm run build:app`, and the e2e suite's global setup, which must not let a
// test run against a stale page or a stale bundle. Duplicating this is how
// those drift apart.

import { build, context } from 'esbuild';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

const root = join(import.meta.dirname, '..');

/** The one definition of how the renderer is built. */
export const options = {
  entryPoints: [join(root, 'renderer', 'app.ts')],
  bundle: true,
  format: 'esm' as const,
  target: 'chrome120',
  outfile: join(root, 'renderer', 'app.js'),
  sourcemap: true,
};

/**
 * Assemble renderer/index.html from the shell and its parts.
 *
 * `<!-- @include parts/x.html -->` is replaced by that file, verbatim. One
 * level, no nesting, no expressions: the page is markup with a seam in it, not
 * a template language, and the seam exists because HTML has no include of its
 * own and the markup HAS to be there before app.js runs — the e2e suite finds
 * its elements in the static page, and so does the failure trap.
 *
 * A missing part throws rather than leaving a hole: a dialog silently absent
 * from the page is a button that opens nothing, three screens away from here.
 */
export function buildPage(): void {
  const shell = readFileSync(join(root, 'renderer', 'page.html'), 'utf8');
  let parts = 0;
  const page = shell.replace(/^([ \t]*)<!-- @include ([^\s]+) -->$/gm, (_m, indent: string, rel: string) => {
    parts++;
    return readFileSync(join(root, 'renderer', rel), 'utf8').replace(/\n+$/, '');
  });
  if (!parts) throw new Error('renderer/page.html has no @include — is it still the shell?');
  // After the doctype, never before it: a comment ahead of <!doctype html> puts
  // the page into quirks mode.
  const banner = '\n<!-- GENERATED by tools/build-renderer.ts from renderer/page.html,\n'
    + '     renderer/parts/ and renderer/style/. Edit those; this file is overwritten. -->';
  writeFileSync(join(root, 'renderer', 'index.html'),
    page.replace(/^(<!doctype html>)/i, `$1${banner}`), 'utf8');
}

/** Build once. Throws if the page is incomplete or the bundle does not compile. */
export async function buildRenderer(): Promise<void> {
  buildPage();
  await build(options);
}

// pathToFileURL, not string surgery: the repo lives under a path with spaces,
// and import.meta.url carries them as %20 while argv[1] has them literal — the
// old endsWith never matched, so `npm start` quietly ran a STALE bundle.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  if (process.argv.includes('--watch')) {
    // The page is assembled once here: esbuild watches the code, and markup
    // edits are a rebuild away rather than a reload away either way.
    buildPage();
    const ctx = await context(options);
    await ctx.watch();
    console.log('watching renderer/app.ts');
  } else {
    await buildRenderer();
    console.log('renderer/index.html and renderer/app.js built');
  }
}
