// Read the original editor's defaults for a freshly placed object.
//
// The way to learn what a new object should look like is not to reason about
// it: place one in the original editor, save, and read what it wrote. Objects
// dropped and left alone are byte-identical apart from Pos/Rot/Shared, so a
// type whose bodies collapse to ONE variant is a default template — that is
// the signal to look for in the output. Two variants mean something was edited
// afterwards (or the placements genuinely differ), and the diff says what.
//
//   npm run object-defaults -- <map.xdb|map.h5m> [Type …]
//
// With no types, every type on the map is summarised. See docs/OBJECT_DEFAULTS.md
// for what this produced, and MAP_PROPERTIES.md for the map-level equivalent.
//
// `--fixture` writes the measurement to tools/fixtures/object-defaults.json
// instead of printing it, so the check in tools/test-defaults.ts runs everywhere
// rather than only on a machine that happens to have the map. Re-run it when the
// reference map gains a type or the measurement is redone.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { readEntries } from '../src/pak.ts';
import { pickMapRel } from '../src/project.ts';

function loadMapXdb(path: string): string {
  if (/\.xdb$/i.test(path)) return readFileSync(path, 'utf8');
  const entries = readEntries(readFileSync(path));
  // Not just any map.xdb: an archive can hold the builder's template too.
  const rel = pickMapRel(entries.map((e) => e.name));
  const entry = rel ? entries.find((e) => e.name === rel) : undefined;
  if (!entry) throw new Error(`${path} holds no map.xdb`);
  return entry.data.toString('utf8');
}

/** Bodies of every <Type>…</Type> in the document, outermost first. */
function bodiesOf(xml: string, type: string): string[] {
  return [...xml.matchAll(new RegExp(`<${type}>([\\s\\S]*?)</${type}>`, 'g'))].map((m) => m[1]!);
}

/** What makes one placement differ from another rather than one default differ. */
function normalise(body: string): string {
  return body
    .replace(/<Pos>[\s\S]*?<\/Pos>/, '<Pos/>')
    .replace(/<Rot>[^<]*<\/Rot>/, '<Rot/>')
    .replace(/<Shared href="[^"]*"\/>/, '<Shared/>')
    .replace(/\r?\n\s*/g, '\n')
    .trim();
}

/**
 * The most-placed variant of a type — the default when the type collapses to
 * one, which is the case the tool is for.
 */
function commonest(variants: Map<string, number>): string {
  return [...variants].sort((a, b) => b[1] - a[1])[0]![0];
}

/**
 * A body as the fixture keeps it: no spell list.
 *
 * A town's guild filter is every spell the INSTALLATION has, so it is neither a
 * constant (it is `x-defaultAll`, resolved from the registry) nor ours to copy
 * into the repository — the fixture describes the shape the editor writes, not
 * the game's content. It is emptied here and skipped in the comparison.
 */
function forFixture(body: string): string {
  return body.replace(/<spellIDs>[\s\S]*?<\/spellIDs>/g, '<spellIDs/>');
}

const args = process.argv.slice(2);
const asFixture = args.includes('--fixture');
const [path, ...wanted] = args.filter((a) => a !== '--fixture');
if (!path) {
  console.error('usage: npm run object-defaults -- <map.xdb|map.h5m> [--fixture] [Type …]');
  process.exit(2);
}

const xml = loadMapXdb(path);
const types = wanted.length
  ? wanted
  : [...new Set([...xml.matchAll(/href="#n:inline\(([A-Za-z]+)\)"/g)].map((m) => m[1]!))].sort();

if (asFixture) {
  const out: Record<string, string> = {};
  for (const type of types) {
    const variants = new Map<string, number>();
    for (const b of bodiesOf(xml, type)) variants.set(normalise(b), (variants.get(normalise(b)) ?? 0) + 1);
    if (variants.size) out[type] = forFixture(commonest(variants));
  }
  const file = join(import.meta.dirname, 'fixtures', 'object-defaults.json');
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, JSON.stringify({
    _: 'Measured defaults: the body the ORIGINAL editor writes for a freshly placed object of each type. Generated by `npm run object-defaults -- <map.h5m> --fixture` from a map made in it for the purpose; see docs/OBJECT_DEFAULTS.md. Pos/Rot/Shared are blanked (they are the placement, not the default) and a town\'s spellIDs is emptied (it is the installation\'s roster, not a constant). Checked by tools/test-defaults.ts, so the check runs without the map.',
    types: out,
  }, null, 2) + '\n');
  console.log(`wrote ${file} — ${Object.keys(out).length} types`);
  process.exit(0);
}

for (const type of types) {
  const bodies = bodiesOf(xml, type);
  const variants = new Map<string, number>();
  for (const b of bodies) {
    const k = normalise(b);
    variants.set(k, (variants.get(k) ?? 0) + 1);
  }
  console.log(`\n### ${type} — ${bodies.length} placed, ${variants.size} distinct`);
  if (variants.size === 1) console.log('(one variant: this is the untouched default)');
  let n = 0;
  for (const [body, count] of variants) {
    console.log(`\n--- variant ${++n} (x${count}) ---\n${body}`);
  }
}
