// A set that reacts to something: the Lua half of an artifact set.
//
// The extension adds NUMBERS to the engine's own arithmetic — a percentage, a
// ceiling — because those live inside calculations no script can reach. What it
// cannot do is decide WHEN: "at the start of every day", "when this building is
// visited", "after that battle" are events, and the engine already hands events
// to Lua. So the two halves split along that line, and this file is the second
// one: the script a set carries, and how it reaches the game.
//
// HOW IT REACHES THE GAME. `scripts/advmap-startup.lua` ends with
// `doFile("/scripts/advmap-common.lua")`, and both are ordinary files under the
// data root, so a mod that carries its own copy runs code on EVERY adventure
// map — the game's own included. Measured, not assumed: see
// docs/NAMES_AND_SCRIPTING.md, where a probe answered both this and whether a
// trigger set here survives a map that sets its own (it does; triggers stack).
//
// WHAT IS GENERATED AND WHAT IS AUTHORED. The header is ours: the set's members
// as the constants a script names them by, and helpers that hide the walk over
// heroes. The body is the author's, verbatim, from a preset they can rewrite —
// the point of a preset being a starting text rather than a hidden wrapper is
// that what runs is what they can see.

import type { ModArtifactSet } from './creature-mod.ts';

/** Where a set's script goes inside the mod. */
export const SCRIPT_DIR = 'scripts/homm5-editor';
/** The game's global script, which we carry a copy of when there is anything to load. */
export const COMMON_SCRIPT = 'scripts/advmap-common.lua';

const EOL = '\r\n';

/**
 * The presets the dialog offers.
 *
 * `newDay` is the one that pays for the whole mechanism: the engine calls it at
 * the start of each day, so nothing polls and nothing can hang the game in a
 * loop that forgets to sleep. `empty` is for an author who knows what they want
 * and would rather not delete someone else's example first.
 */
export const SCRIPT_PRESETS = ['empty', 'newDay'] as const;
export type ScriptPreset = (typeof SCRIPT_PRESETS)[number];

/** A Lua name from a file stem: what the generated symbols are prefixed with. */
const symbolOf = (file: string): string => file.replace(/[^A-Za-z0-9_]/g, '_');

/**
 * The text a preset starts an author off with.
 *
 * It is a whole script, threshold and all, rather than a body with the
 * interesting parts elsewhere: an author who wants the bonus at two pieces
 * instead of three should be able to see the number and change it.
 */
export function presetScript(preset: ScriptPreset, set: Pick<ModArtifactSet, 'file' | 'artifacts'>): string {
  const name = symbolOf(set.file);
  if (preset === 'empty') return '';
  return [
    `-- ${set.file}: runs at the start of every day.`,
    '--',
    '-- MEMBERS and the helpers below are generated from the set; everything from',
    '-- here down is yours. The trigger stacks with any the map sets itself.',
    `function ${name}_NewDay()`,
    '\tfor player = 1, 8 do',
    `\t\tlocal hero = EditorHeroWearing(player, ${name}_MEMBERS, ${set.artifacts.length});`,
    '\t\tif hero then',
    '\t\t\t-- ваш код здесь',
    '\t\t\tRestoreDarkEnergy(player);',
    '\t\tend;',
    '\tend;',
    'end;',
    '',
    `Trigger(NEW_DAY_TRIGGER, "${name}_NewDay");`,
  ].join(EOL) + EOL;
}

/**
 * The generated head of a set's script: its members, by the names a script uses.
 *
 * The ids are the constants `advmap-startup.lua` defines — the mod appends its
 * own artifacts to that list already, so a member of ours is as nameable as a
 * shipped one.
 */
function header(set: ModArtifactSet): string {
  const name = symbolOf(set.file);
  return [
    `-- ${set.name || set.effect} — generated by the editor. Do not edit this head;`,
    '-- it is rewritten whenever the set changes. The code below it is yours.',
    `${name}_MEMBERS = { ${set.artifacts.join(', ')} };`,
    '',
  ].join(EOL) + EOL;
}

/** One file per set that carries a script, plus nothing when none do. */
export function setScriptFiles(sets: readonly ModArtifactSet[]): { path: string; text: string }[] {
  return sets
    .filter((s) => s.script?.trim())
    .map((s) => ({
      path: `${SCRIPT_DIR}/${s.file}.lua`,
      text: header(s) + s.script!.replace(/\r?\n/g, EOL),
    }));
}

/**
 * The game's own `advmap-common.lua`, plus our library and one `doFile` per set.
 *
 * Appended rather than replaced: the 73 lines the game ships are what every
 * mission's script expects to find, and a mod that dropped them would break far
 * more than it added.
 */
export function patchCommonScript(shipped: string, sets: readonly ModArtifactSet[]): string {
  const files = setScriptFiles(sets);
  if (!files.length) return shipped;
  const block = [
    '',
    '-- --- homm5-editor ----------------------------------------------------------',
    '-- Helpers for artifact sets that carry a script, and the scripts themselves.',
    '-- Generated; the editor rewrites this block whenever the mod is built.',
    '',
    '-- How many of `members` this hero is WEARING. A piece in the backpack does',
    '-- not count: HasArtefact\'s third argument is the one the manuals omit.',
    'function EditorWornCount(hero, members)',
    '\tlocal worn = 0;',
    '\tfor index, id in members do',
    '\t\tif HasArtefact(hero, id, 1) then worn = worn + 1; end;',
    '\tend;',
    '\treturn worn;',
    'end;',
    '',
    '-- The first hero of this player wearing at least `count` of them, or nil.',
    'function EditorHeroWearing(player, members, count)',
    '\tlocal heroes = GetPlayerHeroes(player);',
    '\tif heroes == nil then return nil; end;',
    '\tfor index, hero in heroes do',
    '\t\tif EditorWornCount(hero, members) >= count then return hero; end;',
    '\tend;',
    '\treturn nil;',
    'end;',
    '',
    ...files.map((f) => `doFile("/${f.path}");`),
  ].join(EOL);
  return shipped.replace(/\s*$/, EOL) + block + EOL;
}
